### ISSUE TITLE
Failed to process target - context deadline exceeded - ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by Moon-Launch** [root4loot/screener#1]
Therer are 2 errors coming in the Output : 

1) 
[screener] (ERR) Failed to process target https://www.aa/aa: error capturing screenshot for https://www.aa/aa: error navigating to https://www.aa/aa/: context deadline exceeded

even tho https://www.aa/aa exists and is giving the output when we run normally

AND 

2) 
[screener] (ERR) Failed to process target https://www.xx/xx/x: error capturing screenshot for https://www.xx/xx/x: error navigating to https://www.xx/xx/x: navigation failed: net::ERR_NAME_NOT_RESOLVED

even tho https://www.xx/xx/x exists and is giving the output when we run normally

**Comment by root4loot** [comment]
Hi @jhammond2012

Thank you reporting this. A fix has been pushed and build is now passing. Can you confirm?

```
go install github.com/root4loot/screener@cad7bb59b371ccf7494702b4ff5a48a23c1b8326
```

**Comment by Moon-Launch** [comment]
> go install github.com/root4loot/screener@cad7bb59b371ccf7494702b4ff5a48a23c1b8326

![image](https://github.com/user-attachments/assets/f97b21c5-daca-4d7e-9983-87a07acd9abe)

**Comment by Moon-Launch** [comment]
Installed using: go install github.com/root4loot/screener/cmd/screener@latest
and seems everything working for now 

so closing this comment 
will reopen if any issues 

Regards
- Shamim

**Comment by Moon-Launch** [comment]
Exerything was working good suddenly this error pop up : 
![image](https://github.com/user-attachments/assets/80c72997-5890-47a4-a7a3-feb4b245e79b)

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7bac06]

**Comment by root4loot** [comment]
Hm. Let me look into this. Get back to you shortly.

**Comment by root4loot** [comment]
@jhammond2012 spotted the issue and should now be fixed. Can you confirm once more? Will improve tests later.

If updating with `@latest` does not help then try:

```
go install github.com/root4loot/screener/cmd/screener@cd6c7ae5ca4a6ff09cc453d6b09d6cbaac653810
```

Let me know if that does it. Appreciate the feedback

**Comment by Moon-Launch** [comment]
It seems like the error still exists : 

![image](https://github.com/user-attachments/assets/48474152-9073-4fa1-aa62-0dda50a688fb)
![image](https://github.com/user-attachments/assets/fda90aeb-06b3-4bfe-a5cd-70839a6e2bcc)

Also I got :
[screener] (ERR) Failed to process target https://....: error capturing screenshot for https://....: error navigating to https://.../: context deadline exceeded
![image](https://github.com/user-attachments/assets/7278e1aa-c7eb-4c09-a1fb-f6ce53f936a2)

**Comment by root4loot** [comment]
@jhammond2012 The output suggest you are not running the latest version.

Based on the segfault, you are running `v0.0.0-20241016145244-cad7bbS9b371` but the patched version should be `v0.0.0-20241016174605-cd6c7ae5ca4a`

It is likely that you have two binaries installed. Did you move the `screener` binary at some point? The following command should point to `/home/kali/go/bin/screener`. It could be that your `GOBIN` is not correctly set up. 

```
which screener
```
